apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice1
  labels:
    app: productservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice1
  template:
    metadata:
      name: productservice1
      labels:
        app: productservice1
    spec:
      containers:
        - name: productservice1
          image: gvt3/productservicev1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      